### ISSUE TITLE
q chainedtick.q :5010 -p 5110 -t 1000 example from documentation dosen't seem to work

### ISSUE THREAD

**Issue by ljubicic** [KxSystems/kdb#1]

**Comment by ljubicic** [comment]
q chainedtick.q :5010 -p 5110 -t 1000

**Comment by CharlieSkelton-Kx** [comment]
Please can you give us more details about what "doesn't seem to work"?

**Comment by ljubicic** [comment]
sure, yes bit vague or even my mis-undersating, but see file /tick/chainedtick.q
line 8 references u.q and this file is not in repo
     \l tick/u.q

**Comment by CharlieSkelton-Kx** [comment]
I see. It assumes you have installed kdb+tick available from https://github.com/KxSystems/kdb-tick
See also http://code.kx.com/q/tutorials/startingq/tick/

**Comment by ljubicic** [comment]
thanks, got it.
