### ISSUE TITLE
c.obj (w32 or w64) missing 

### ISSUE THREAD

**Issue by TheFausap** [KxSystems/kdb#10]
Hello,

in  order to compile under windows, I should need a c.obj, but I cannot find it.

Maybe I'm looking in the wrong place.

thanks,
Fausto

**Comment by CharlieSkelton-Kx** [comment]
I believe you're looking for c_static.lib
https://github.com/KxSystems/kdb/blob/master/w32/c_static.lib
https://github.com/KxSystems/kdb/blob/master/w64/c_static.lib

**Comment by CharlieSkelton-Kx** [comment]
see https://github.com/KxSystems/kdb/commit/badfab916ad773fd9f0bd528044c4189376f67be

**Comment by TheFausap** [comment]
I'm referring to that c.obj file mentioned in the comments here : 

https://github.com/KxSystems/cookbook/blob/master/c/csv.c

specifically 

```
// windows:
//  start the x86 or 64 bit version of build environment, then: cl -DKXVER=3 /MD csv.c c.obj ws2_32.lib
//  obtain c.obj from http://kx.com/q/w32/ or w64/
```
Is this an outdated information ?

**Comment by TheFausap** [comment]
:) I’m sorry. Everything is ok now. 
Thank you !
