### ISSUE TITLE
jdbc driver returns no rows, just header

### ISSUE THREAD

**Issue by lozbrown** [KxSystems/kdb#16]
I've been attempting to test the JDBC driver with a view to later useing it to integrate Alation Data catalog
I set up the connection with the driver
![image](https://user-images.githubusercontent.com/9961593/70746579-fe8afc80-1d1d-11ea-84ad-b09a8a74860b.png)

But a query returns no rows... I can assure you that this definitely does return rows on a qpad/qstudio
![image](https://user-images.githubusercontent.com/9961593/70745923-cb943900-1d1c-11ea-89e9-17f2e239f0dc.png)

i can see from the logs the query it actually runs is as follows
```
 .z.pg: ([]TABLE_TYPE:`TABLE`VIEW)^M
.z.pg: {[maxRows;fetchSize;fn;args]$[not .Q.qt r:value[fn]args;::;count r:select[maxRows]from 0!r;{neg[.z.w]@/:-1_x;last x}(0N;fetchSize)#r;r]}[0;2147483647], .o.ex, q)select from trade^M
```

is there some property i should be supplying to the driver?

**Comment by CharlieSkelton-Kx** [comment]
The trace is helpful. It shows that the application is setting max rows to 0, hence it is limiting the result set length to 0 rows. Somewhere the app is calling public void setMaxRows(int n) at https://github.com/KxSystems/kdb/blob/master/c/jdbc.java#L137
I don't know the app, but maybe you can ask their support why they would do that?

**Comment by CharlieSkelton-Kx** [comment]
SQL Workbench/J has a maxrows field under edit menu. It's on the status bar at the bottom of the sql editor window, and seems to default to 0. If I set it to something reasonable, it runs just fine.

**Comment by lozbrown** [comment]
@CharlieSkelton-Kx 
Thanks, that wasn't obvious but has made it work much better but one of my columns seems to upset this driver.

**Comment by CharlieSkelton-Kx** [comment]
thanks for the details. To fix that exception, we've updated https://github.com/KxSystems/kdb/blob/master/c/jdbc.jar
The jdbc driver passes the q or sql text to the server. For SQL support you should take the ps.k file from the odbc3 zip file here https://code.kx.com/v2/interfaces/q-server-for-odbc3/
and ensure that is loaded into your kdb+ process. ps.k is the sql transpiler.
Eventually, ps.k will be made available outside of odbc3.

**Comment by CharlieSkelton-Kx** [comment]
we've also updated the driver to fix MaxRows==0 and FetchSize==0 to be interpreted as 'unlimited' - but actually 2 Billion.
thanks for pointing out these issues in our driver.

**Comment by lozbrown** [comment]
Thanks
This works a lot better now. Addtional the ps.k seems to work.

![image](https://user-images.githubusercontent.com/9961593/71006632-876ab500-20dd-11ea-8aae-e661298f2f35.png)
