### ISSUE TITLE
Missing JavaDoc of custom data types e.g. Dict 

### ISSUE THREAD

**Issue by pranasblk** [KxSystems/kdb#7]
Theoretically available but in reality faked one in a hurry to pass internal QA ..
https://buabook.github.io/javadoc/java-kdb-communication/com/kx/c.Dict.html

**Comment by sv** [comment]
Would you be willing to push your javadoc updates as a PR?

**Comment by sv** [comment]
This has been addressed in javakdb https://github.com/KxSystems/javakdb/blob/master/src/kx/c.java
