### ISSUE TITLE
jdbc datetime$ ClassCastException

### ISSUE THREAD

**Issue by s-b-u** [KxSystems/kdb#8]
ResultSetMetaData reports SQL-Type 93 = java.sql.Types.TIMESTAMP for a column of type datatime$.
Therefore it should be possible to retrieve the data by ResultSet#getTimestamp at this column, but the underlying object is of type java.util.Date and can't be cast to java.sql.Timestamp and a ClassCastException is thrown instead.

**Comment by sv** [comment]
Could you provide reproducer/test? Feel free to submit PR if you have a fix ready
